### ISSUE TITLE
Crash on reading PRG with no variation

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab/gramtools#22]
cat zam
AACGTT

 cat zam.all.kmers 
AA
AC
CG
GT
TT

cat zam.mask_alleles 
0 0 0 0 0 0
cat zam.mask_sites 
0 0 0 0 0 0

/home/zam/dev/git/gramtools/src/gramtools --prg zam5 --csa out/csa  --ps zam.\
mask_sites  --pa zam.mask_alleles  --co out/covg --ro out/read --po out/bin -\
-log out/memlog --ksize 2 --kfile zam.all.kmers --input read.fa

-----
Mon Jul 25 23:37:15 2016
Start CSA construction
PRG size: 6
Alphabet size: 0

-----
Mon Jul 25 23:37:16 2016
End CSA construction

6 6
Segmentation fault

Run through valgrind:

-----
Mon Jul 25 23:38:00 2016
End CSA construction

6 6
==46905== Invalid read of size 8
==46905==    at 0x408BCC: std::vector<int, std::allocator<int> >::size() const (stl_vector.h:626)
==46905==    by 0x417702: parse_masks(std::vector<unsigned long, std::allocator<unsigned long> >&, std::vector<int, std::allocator<int> >&, std::string, std::string, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&) (parse_masks.cpp:57)
==46905==    by 0x4422AA: main (map.cpp:146)
==46905==  Address 0xfffffffffffffff0 is not stack'd, malloc'd or (recently) free'd
==46905== 
==46905== 
==46905== Process terminating with default action of signal 11 (SIGSEGV)
==46905==  Access not within mapped region at address 0xFFFFFFFFFFFFFFF0
==46905==    at 0x408BCC: std::vector<int, std::allocator<int> >::size() const (stl_vector.h:626)
==46905==    by 0x417702: parse_masks(std::vector<unsigned long, std::allocator<unsigned long> >&, std::vector<int, std::allocator<int> >&, std::string, std::string, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&) (parse_masks.cpp:57)
==46905==    by 0x4422AA: main (map.cpp:146)

Run through gdb and we see this

Program received signal SIGSEGV, Segmentation fault.
0x0000000000408bcc in std::vector<int, std::allocator<int> >::size (
    this=0xffffffffffffffe8)
    at /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/bits/stl_vector.h:626
626	      { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
(gdb) bt
#0  0x0000000000408bcc in std::vector<int, std::allocator<int> >::size (
    this=0xffffffffffffffe8)
    at /opt/centos/devtoolset-1.1/root/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../include/c++/4.7.2/bits/stl_vector.h:626
#1  0x0000000000417703 in parse_masks (
    mask_s=std::vector of length 6, capacity 8 = {...}, 
    mask_a=std::vector of length 6, capacity 8 = {...}, sites_fname=
    "/data2/users/zam/analyses/2016/0720_debug_gramtools/zam5.mask_sites", 
    alleles_fname=
    "/data2/users/zam/analyses/2016/0720_debug_gramtools/zam5.mask_alleles", 
    covgs=std::vector of length 0, capacity 0) at ./parse_masks.cpp:57
#2  0x00000000004422ab in main (argc=23, argv=0x7fffffffcaa8)
    at ./map.cpp:146
(gdb) frame 2
#2  0x00000000004422ab in main (argc=23, argv=0x7fffffffcaa8)
    at ./map.cpp:146
146		uint64_t maxx=parse_masks(mask_s,mask_a,_sitemask,_allmask,covgs);
(gdb) p mask_s
$1 = std::vector of length 6, capacity 8 = {0, 0, 0, 0, 0, 0}
(gdb) p mask_a
$2 = std::vector of length 6, capacity 8 = {0, 0, 0, 0, 0, 0}
(gdb) p _sitemask
$3 = "/data2/users/zam/analyses/2016/0720_debug_gramtools/zam5.mask_sites"
(gdb) p covgs
$4 = std::vector of length 0, capacity 0
(gdb) frame 1
#1  0x0000000000417703 in parse_masks (
    mask_s=std::vector of length 6, capacity 8 = {...}, 
    mask_a=std::vector of length 6, capacity 8 = {...}, sites_fname=
    "/data2/users/zam/analyses/2016/0720_debug_gramtools/zam5.mask_sites", 
    alleles_fname=
    "/data2/users/zam/analyses/2016/0720_debug_gramtools/zam5.mask_alleles", 
    covgs=std::vector of length 0, capacity 0) at ./parse_masks.cpp:57
57	  cout<<"Covgs dim"<<covgs.size()<<" "<<covgs.front().size()<<" "<<covgs.back().size()<<endl;
(gdb) l
52	    mask_a.push_back(0);
53	    }*/
54	
55	  cout<<endl<<mask_s.size()<<" "<<mask_a.size()<<endl;
56	
57	  cout<<"Covgs dim"<<covgs.size()<<" "<<covgs.front().size()<<" "<<covgs.back().size()<<endl;
58	  return(no_sites+1); //no_sites is last odd number in mask_sites, but alphabet size is the even number corresponding to it
59	}
(gdb) p covgs.size()
$5 = 0
(gdb) p covgs.front()
$6 = <error reading variable: Cannot access memory at address 0x8>
(gdb) 

ie annoying thing - crashes if you call front() on an empty covgs array trying to print this

 cout<<"Covgs dim"<<covgs.size()<<" "<<covgs.front().size()<<" "<<covgs.back().size()<<endl;

**Comment by iqbal-lab** [comment]
removing that print fixes the bug

**Comment by iqbal-lab** [comment]
Fixed in 8ce44762f1261e8410fba5f58b7a87241ac31679
